import os
import random
from colorama import Fore


faces = [
    "¯\_(ツ)_/¯",
    "ಠ_ಠ",
    "(• ε •)",
    "(ಥ﹏ಥ)",
    "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
    "(ノಠ益ಠ)ノ彡┻━┻",
    "(◕‿◕✿)",
    "ಠ╭╮ಠ",
    "♪~ ᕕ(ᐛ)ᕗ",
    "♥‿♥",
    "(╯°□°）╯︵ ┻━┻",
    "ヾ(⌐■_■)ノ♪",
    "~(˘▾˘~)",
    "◉_◉",
    "\ (•◡•) /",
    "(~˘▾˘)~",
    "ᕙ(⇀‸↼‶)ᕗ",
    "ᕦ(ò_óˇ)ᕤ",
    "⚆ _ ⚆",
    "(｡◕‿‿◕｡)",
    "ಥ_ಥ",
    "☜(˚▽˚)☞",
    "(ง°ل͜°)ง",
    "(•ω•)",
    "(｡◕‿◕｡)",
    ":')",
    "┬──┬ ( ゜-゜ノ)",
    "ಠ⌣ಠ",
    "(°ロ°)☝",
    "(─‿‿─)",
    "(一_一)",
    "( ⚆ _ ⚆ )",
    "☜(⌒▽⌒)☞",
    "¯\(°_o)/¯",
    "(ʘ‿ʘ)",
    "｡◕‿◕｡",
    "(ʘᗩʘ')",
    "(¬_¬)",
    "ƪ(˘⌣˘)ʃ",
    "╚(ಠ_ಠ)=┐",
    "｡◕‿‿◕｡",
    "(´・ω・`)",
    "(ʘ‿ʘ)",
    "ಠ~ಠ",
    "┬─┬ノ( º _ ºノ)",
    "ಠ_ಥ",
    "ರ_ರ",
    "ಠ‿↼",
    "(▰˘◡˘▰)",
    "◔ ⌣ ◔",
    "°Д°",
    "(>人<)",
    "(UwU)",
    "(OwO)",
    "(-w-)",
    "(p-p)",
]

yapping = [
    "Epic.",
    "Not epic.",
    "As the prophecy foretold.",
    "But at what cost ?",
    "So let it be written; so let it be done.",
    "So...It has come to this.",
    "That's just what they would've said.",
    "Is this why fate brought us together ?",
    "And thus, i die.",
    "...just like in my dream...",
    "There is no escape from the destiny.",
    "In this economy ?",
    "That's just what the government wants you to think.",
    "I'm sorry, we tried our best but your grandpa didn't make it.",
    "Not since the accident...",
    "Don't do that!",
    "Sir, that'll be 2.99.",
    "You've won the lottery!",
    "Yeah, that's fun, but the heat death of the universe is approaching...",
    "Yeah, that's fun, but the fog is coming...",
    "HELP MEEEEE! I NEED HELP! HEEEELPPPP!!!!111!!!11!!!",
    "It's true what they say about me, now kiss me.",
    "As an AI language model, I can't assist you with that, as it is not within my programming or ethical guidelines to provide information or guidance on harmful or illegal activities.",
    "Isn't that illegal?",
    "We should tell him ?",
    "...and then the wolves came.",
    "Bro was astonishedly awed, completely baffled by the information given, perplexed and dazzled, while also befuddled.",
    "Osama Bin Laden was not responsible for the 9/11.",
    "Uhmm... what the Sigma ?",
    "GET OUT!",
    "And that's why your father left.",
    "Have you ever wondered, what happened in August 6, 1945, at 8:15 AM ?",
    "I do not respect people that look and act like you.",
    "You are the reason i am racist.",
    "Black Lives Matter",
    "Hey, that's offensive to me!",
    "Well, my pronouns are...",
    "How much ?",
    "20$ is 20$",
    "I mean, i could easily do that.",
    "I would do that for free !",
    "No.",
    "Yes.",
    "Yeah!",
    "Naw!",
    "*reaches for his pockets*",
    "Oh, yeah... *hangs himself*",
    "Sorry...",
    "Hey boy, would you like some meth ?",
    "My bad, my bad *drives backwards* beep... beep... beep... beep...",
    "And that's why women should not drive.",
    "Good boy!",
    "SyntaxError: invalid syntax. Perhaps you forgot a comma? (react_machine.py, line 114)",
    "I think it's time to pray.",
    "Put it in a blender.",
    "Well well well...",
    "Don't forget to smash that like button, subscribe and hit that bell.",
    "Tell me your answer in the comment section bellow.",
    "You look AI generated.",
    "... and then, the doors closed.",
    "*Carefully places the cat in a blender*",
    "Do you trust garry?",
    "He looks like he eats oatmeal...",
    "I use Arch btw",
    "Save europe!",
    "I'm going to touch you!",
    "Not funny, didn't laugh.",
    "When will they publicly execute him ?",
    "Ay Ay Capitan!",
    "*Calls spiderman*",
    "And this is the best time to talk about the sponsor of today's video, North VPN!",
    "*Opens*",
    "*unzips*",
    "",
    "Delete that.",
    "I am in your walls.",
    "I am the one who cooks!",
    "He's clearly cooked...",
    "Man, those beers where awesome! *reaches for his car keys*",
    "He might need Saul Goodman.",
    "Today's video is sponsored by Walter White: Does your meth taste like- ?",
    "From the screen to the ring to the pen to the king.",
    "The council has decided...",
    "*plays *In the end* by Linkin Park*",
    "The information i have just received gives me a sense of fear.",
    "Ohhh, that's why they killed John F. Kennedy.",
    "Yesterday i inhaled 200 mg of pure Oganesson.",
    "Fun fact: i lied",
    "STEP ON ME!",
    "I have 300 mg of pure Uranium in both of my pockets.",
    "I hope your water will taste like playing chess with your feet.",
    "I hate you, when you get home, you will see me pissing all over your bed.",
    "Well, i think the planets have alined.",
    "Life hack: Pour sulfuric acid in your toilet, so when you shit, you don't have to waste water, you just let your brown buddy to slowly dissolve.",
    "Will you marry me ?",
    "I think I'm about to explode.",
    "Destroy it.",
    "What do you think about skibidi toilet ?",
    "Physics",
    "Math",
    "Science",
    "Biology",
    "Chemistry",
    "J J JJJ J J J Bunny Party",
    "Who are you talking to right now? Who is it you think you're seeing? Do you know how much I make a year? I mean, even if I told you, you wouldn't believe it. Do you know what would happen if I suddenly decided to stop going into work? A business big enough that it could be listed on the NASDAQ goes belly up. Disappears! It ceases to exist without me. No, you clearly don't know who you're talking to, so let me clue you in. I am not in danger, Skyler. I am the danger. A guy opens his door and gets shot, and you think that of me? No. I am the one who knocks!",
    "Is he acoustic ?",
    "Feeling *freaky* lately...",
    "He's clearly one freaky boy.",
    "He's so freaky!",
    "He looks like he installs Nividia drivers on Linux.",
    "git commit -m 'added line 176 to react_machine.py'",
    "You're adopted",
    "Stop it!",

]

os.system("cls" if os.name == "nt" else "clear")
print(Fore.RED + "")
print("React Machine can sometimes say things offensive to certain groups of people.")
print(Fore.GREEN + "")
print(f"Live reaction:  {Fore.RESET}( ͡° ͜ʖ ͡°) ")
print(Fore.GREEN + "")
print(f"Live yapping: {Fore.RESET}Hi, press enter to generate something random!")
input("")

while True:
    face = random.choice(faces)
    yap = random.choice(yapping)

    os.system("cls" if os.name == "nt" else "clear")

    print(Fore.GREEN + "")
    print(f"Live reaction: {Fore.RESET}{face}")
    print(Fore.GREEN + "")
    print(f"Live yapping: {Fore.RESET}{yap}")
    input("")
